### PR TITLE
Add .js extensions to d.ts exports

### PR DESCRIPTION
**Pull request by benasher44**
Fixes one of the core issues in #28

### CODE REVIEW

**Comment by benasher44** [comment]
Ah @nikku, I believe this is the install issue I was seeing that prompted #30. Can that one be merged, and then I'll rebase this one?

**Comment by nikku** [comment]
I'm on, trying to merge this :crossed_fingers:.

**Comment by benasher44** [comment]
Updated with main now that #32 has landed — CI should pass now

**Comment by nikku** [comment]
I added some additional validation for strict and ESM modes via https://github.com/bpmn-io/min-dash/pull/31/commits/826b1bc2172ad243c3c1f38416de3b722922ed1b.

**Comment by nikku** [comment]
Works on CI :tm:

**Comment by benasher44** [comment]
Thank you!

**Pull request merged**
